spring.application.name=spring-gift
jwt.secret=${JWT_SECRET:a-string-secret-at-least-256-bits-long}
jwt.expiration=${JWT_EXPIRATION:3600000}
kakao.login.client-id=${KAKAO_CLIENT_ID:}
kakao.login.client-secret=${KAKAO_CLIENT_SECRET:}
kakao.login.redirect-uri=${KAKAO_REDIRECT_URI:http://localhost:8080/api/auth/kakao/callback}
kakao.login.authorization-uri=${KAKAO_AUTHORIZATION_URI:https://kauth.kakao.com/oauth/authorize}
kakao.login.token-base-uri=${KAKAO_TOKEN_BASE_URI:https://kauth.kakao.com}
kakao.login.token-path=${KAKAO_TOKEN_PATH:/oauth/token}
kakao.login.user-info-base-uri=${KAKAO_USER_INFO_BASE_URI:https://kapi.kakao.com}
kakao.login.user-info-path=${KAKAO_USER_INFO_PATH:/v2/user/me}
